api_url: '' # https://api.example.com/api/v2/ps/update
api_key: '' # 设置的key
report_time: 1 # 上报时间间隔，单位秒
keywords: # 关键词屏蔽，数组形式
  - 'pronhub'
replace:
  - 'idea64'
  - 'Firefox'
replace_to:
  - 'Code'
  - 'Chrome'
